### ISSUE TITLE
Nav bar buttons click in mobile view without explicitly selecting the button

### ISSUE THREAD

**Issue by milindvishnoi** [grey-software/grey.software#42]
Please watch the video for further explanation [here.](https://www.loom.com/share/e9f118041f7b495c9387fab1cb981bf7)

**Comment by ArsalaBangash** [comment]
Pretty cool loom recording. I also found another issue with the mobile navbar: 
![image](https://user-images.githubusercontent.com/19757203/92536404-9ebb7680-f207-11ea-9042-2d93db69344a.png)

Let's fix both of these in a PR!
