### ISSUE TITLE
🐛 Bug: GitHub button in Header Navigation leads to Discord server

### ISSUE THREAD

**Issue by pascalwengerter** [grey-software/grey.software#53]
### Expected Behavior 🧭
I was expecting to be redirected to [Grey Software's GitHub page](https://github.com/grey-software/) upon clicking the "Contribute" button in the main/header navigation.

### Current Behavior 🔍 
I was redirected to Discord (which is fair enough, but I wasn't looking for the "Community" link. Just wanted to look around the whole org & its repos before joining the chat 😉 )

### Possible Solution 🛠️ 
Either change the logo & text in the button and/or add a second one so there's one for **Contribution** on GitHub and a dedicated second **community** button for Discord.

**Comment by ArsalaBangash** [comment]
Hi @pascalwengerter! I've updated the website's navbar and drawer with your requested changes :) 

If you have other suggestions, please comment below or close the issue if the changes are up to your preferences.

**Comment by pascalwengerter** [comment]
Thanks, looks great to me!
